// Code generated by mockery v2.53.6. DO NOT EDIT.

package repomocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "e-commerce/model"
)

// CustomerSignupRepository is an autogenerated mock type for the CustomerSignupRepository type
type CustomerSignupRepository struct {
	mock.Mock
}

// CreateCustomerAccount provides a mock function with given fields: customer
func (_m *CustomerSignupRepository) CreateCustomerAccount(customer *model.Customer) error {
	ret := _m.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomerAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Customer) error); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *CustomerSignupRepository) FindByEmail(ctx context.Context, email string) (*model.Customer, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *model.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Customer, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Customer); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByPhoneNumber provides a mock function with given fields: ctx, phone_number
func (_m *CustomerSignupRepository) FindByPhoneNumber(ctx context.Context, phone_number string) (*model.Customer, error) {
	ret := _m.Called(ctx, phone_number)

	if len(ret) == 0 {
		panic("no return value specified for FindByPhoneNumber")
	}

	var r0 *model.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Customer, error)); ok {
		return rf(ctx, phone_number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Customer); ok {
		r0 = rf(ctx, phone_number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone_number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkEmailVerified provides a mock function with given fields: ctx, email
func (_m *CustomerSignupRepository) MarkEmailVerified(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for MarkEmailVerified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkPhoneNumberVerified provides a mock function with given fields: ctx, phoneNumber
func (_m *CustomerSignupRepository) MarkPhoneNumberVerified(ctx context.Context, phoneNumber string) error {
	ret := _m.Called(ctx, phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for MarkPhoneNumberVerified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, phoneNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCustomerSignupRepository creates a new instance of CustomerSignupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerSignupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerSignupRepository {
	mock := &CustomerSignupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
