// Code generated by mockery v2.53.6. DO NOT EDIT.

package repomocks

import (
	otprepository "e-commerce/repository/otp_repository"

	mock "github.com/stretchr/testify/mock"
)

// OTPRepository is an autogenerated mock type for the OTPRepository type
type OTPRepository struct {
	mock.Mock
}

// GetOTP provides a mock function with given fields: identifier
func (_m *OTPRepository) GetOTP(identifier string) (*otprepository.OTPData, error) {
	ret := _m.Called(identifier)

	if len(ret) == 0 {
		panic("no return value specified for GetOTP")
	}

	var r0 *otprepository.OTPData
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*otprepository.OTPData, error)); ok {
		return rf(identifier)
	}
	if rf, ok := ret.Get(0).(func(string) *otprepository.OTPData); ok {
		r0 = rf(identifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*otprepository.OTPData)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(identifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveOTP provides a mock function with given fields: identifier, otp
func (_m *OTPRepository) SaveOTP(identifier string, otp string) error {
	ret := _m.Called(identifier, otp)

	if len(ret) == 0 {
		panic("no return value specified for SaveOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(identifier, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOTPRepository creates a new instance of OTPRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOTPRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OTPRepository {
	mock := &OTPRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
