// Code generated by mockery v2.53.6. DO NOT EDIT.

package servicemocks

import (
	context "context"
	customerrequest "e-commerce/dto/request/customer_request"

	mock "github.com/stretchr/testify/mock"
)

// CustomerSignupService is an autogenerated mock type for the CustomerSignupService type
type CustomerSignupService struct {
	mock.Mock
}

// CustomerSignup provides a mock function with given fields: req, ctx
func (_m *CustomerSignupService) CustomerSignup(req customerrequest.CustomerSignupRequest, ctx context.Context) error {
	ret := _m.Called(req, ctx)

	if len(ret) == 0 {
		panic("no return value specified for CustomerSignup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(customerrequest.CustomerSignupRequest, context.Context) error); ok {
		r0 = rf(req, ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCustomerSignupService creates a new instance of CustomerSignupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerSignupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerSignupService {
	mock := &CustomerSignupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
