// Code generated by mockery v2.53.6. DO NOT EDIT.

package servicemocks

import mock "github.com/stretchr/testify/mock"

// OTPSender is an autogenerated mock type for the OTPSender type
type OTPSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: identifier, otp
func (_m *OTPSender) Send(identifier string, otp string) error {
	ret := _m.Called(identifier, otp)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(identifier, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOTPSender creates a new instance of OTPSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOTPSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *OTPSender {
	mock := &OTPSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
