// Code generated by mockery v2.53.6. DO NOT EDIT.

package servicemocks

import mock "github.com/stretchr/testify/mock"

// OTPService is an autogenerated mock type for the OTPService type
type OTPService struct {
	mock.Mock
}

// GenerateOTP provides a mock function with given fields: identifier, otp_type
func (_m *OTPService) GenerateOTP(identifier string, otp_type string) (string, error) {
	ret := _m.Called(identifier, otp_type)

	if len(ret) == 0 {
		panic("no return value specified for GenerateOTP")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(identifier, otp_type)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(identifier, otp_type)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(identifier, otp_type)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyOTP provides a mock function with given fields: identifier, otp_type, otp
func (_m *OTPService) VerifyOTP(identifier string, otp_type string, otp string) error {
	ret := _m.Called(identifier, otp_type, otp)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(identifier, otp_type, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOTPService creates a new instance of OTPService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOTPService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OTPService {
	mock := &OTPService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
