// Code generated by mockery v2.53.6. DO NOT EDIT.

package servicemocks

import (
	otpservice "e-commerce/service/otp_service"

	mock "github.com/stretchr/testify/mock"
)

// SenderFactory is an autogenerated mock type for the SenderFactory type
type SenderFactory struct {
	mock.Mock
}

// GetSender provides a mock function with given fields: _a0
func (_m *SenderFactory) GetSender(_a0 otpservice.OTPType) (otpservice.OTPSender, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetSender")
	}

	var r0 otpservice.OTPSender
	var r1 error
	if rf, ok := ret.Get(0).(func(otpservice.OTPType) (otpservice.OTPSender, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(otpservice.OTPType) otpservice.OTPSender); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(otpservice.OTPSender)
		}
	}

	if rf, ok := ret.Get(1).(func(otpservice.OTPType) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSenderFactory creates a new instance of SenderFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSenderFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *SenderFactory {
	mock := &SenderFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
