// Code generated by mockery v2.53.6. DO NOT EDIT.

package servicemocks

import mock "github.com/stretchr/testify/mock"

// TemplateRenderer is an autogenerated mock type for the TemplateRenderer type
type TemplateRenderer struct {
	mock.Mock
}

// Render provides a mock function with given fields: path, msg
func (_m *TemplateRenderer) Render(path string, msg interface{}) (string, error) {
	ret := _m.Called(path, msg)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, interface{}) (string, error)); ok {
		return rf(path, msg)
	}
	if rf, ok := ret.Get(0).(func(string, interface{}) string); ok {
		r0 = rf(path, msg)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, interface{}) error); ok {
		r1 = rf(path, msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTemplateRenderer creates a new instance of TemplateRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTemplateRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TemplateRenderer {
	mock := &TemplateRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
